# Generated by Django 5.0.6 on 2024-06-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='birthdate',
        ),
    ]
